version: 2.1

aliases:
  - &branch-filter
    branches:
      only:
        - dev
        - main

x-machine: &x-machine
  image: ubuntu-2004:202111-02 # always update to latest image from https://circleci.com/docs/2.0/configuration-reference/#available-machine-images

jobs:
  python_tests:
    working_directory: /tmp/project
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements-dev.txt
      - run:
          name: black
          command: black --check --line-length 120 .
      - run:
          name: prospector
          command: prospector
  terraform_format:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:1.1.6
    steps:
      - checkout
      - run:
          name: terraform format
          command: terraform fmt -check -recursive
  sast_terraform:
    machine: *x-machine
    parameters:
      rootdir:
        type: string
    steps:
      - checkout
      - run:
          name: install checkov
          command: |
            pip3 install --upgrade checkov
            echo $PATH
            checkov --version
            which checkov
      - run:
          name: generate & upload json report
          command: |
            checkov --config-file .config/sast_terraform_checkov_json.yml 1> /tmp/${GITHUB_SHA}.json --directory << parameters.rootdir >>
            echo "TODO uploading /tmp/${GITHUB_SHA}.json to <somewhere>"
      - run:
          name: test code
          command: >
            checkov
            --config-file .config/sast_terraform_checkov_cli.yml
            --directory << parameters.rootdir >>
  plan:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:1.1.6
    steps:
      - checkout
      - run:
          name: terraform state bucket variables
          command: |
            echo "export TERRAFORM_STATE_BUCKET=$TERRAFORM_STATE_BUCKET" >> $BASH_ENV
            echo "export TERRAFORM_STATE_KEY=$TERRAFORM_STATE_KEY" >> $BASH_ENV
            echo "export TERRAFORM_STATE_REGION=$TERRAFORM_STATE_REGION" >> $BASH_ENV
      - run:
          name: terraform init
          command: "set -x;terraform init -backend-config=bucket=$TERRAFORM_STATE_BUCKET -backend-config=key=$TERRAFORM_STATE_KEY -backend-config=region=$TERRAFORM_STATE_REGION"
      - run:
          name: set terraform workspace
          command: |
            if [ "$CIRCLE_BRANCH" = "main" ]; then
              terraform workspace select prd || terraform workspace new prd
            else
              terraform workspace select "$CIRCLE_BRANCH" || terraform workspace new "$CIRCLE_BRANCH"
            fi
      - run:
          name: terraform plan
          command: terraform plan -out tfplan
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    docker:
      - image: python:3.9
    steps:
      - attach_workspace:
          at: .
      - run:
          name: install terraform
          command: |
            wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.1.6/terraform_1.1.6_linux_amd64.zip
            unzip -d /usr/local/bin /tmp/terraform.zip
      - run:
          name: install virtualenv
          command: pip install virtualenv
      - run:
          name: terraform apply
          command: terraform apply -auto-approve tfplan
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  cd:
    jobs:
      - python_tests
      - terraform_format
      - sast_terraform:
          rootdir: .
      - plan:
          filters: *branch-filter
          requires:
            - python_tests
            - terraform_format
            - sast_terraform
      - approve:
          filters: *branch-filter
          type: approval
          requires:
            - plan
      - apply:
          filters: *branch-filter
          requires:
            - approve